### ISSUE TITLE
failOnRisky, failOnWarning exit statements are never reached

### ISSUE THREAD

**Issue by gskema** [sebastianbergmann/phpunit#3163]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.2.4
| PHP version         | 7.1.17
| Installation Method | Composer

https://github.com/sebastianbergmann/phpunit/blob/00bc0b93f0ff4f557e9ea766557fde96da9a03dd/src/TextUI/TestRunner.php#L703-L709

We enter line 703 when line 702 `::wasSuccessful()` passed (`empty($this->errors) && empty($this->failures) && empty($this->warnings);`). Therefore `$risky` and `$warning` count is 0 and the statements in lines 704 and 708 are never reached.

The exit code still ends up being `1` because these conditions don't pass and default value is `1`:

https://github.com/sebastianbergmann/phpunit/blob/00bc0b93f0ff4f557e9ea766557fde96da9a03dd/src/TextUI/Command.php#L208-L214

I found this while investigating who to configure tests to fail (exit code 2?) on warning "The data provider specified for ... is invalid." If I understand correctly, this is not possible yet with the current set of options. We found a test in production that was skipped because of this warning at the raises my concern.

**Comment by woodcockjosh** [comment]
Not stale for me bot

**Comment by woodcockjosh** [comment]
Looks like we can just take put those checks above $result->wasSuccessful() and it should work. Will try to get in a pull request.

**Comment by sebastianfeldmann** [comment]
This is already fixed in version `6.5`

**Comment by woodcockjosh** [comment]
@sebastianbergmann @sebastianfeldmann  its not fixed. Please see below configurations to reproduce.

phpversion
`josh@Joshs-MacBook-Pro-2:~/.../unit-tests$ phpunit --version
PHPUnit 7.3.2 by Sebastian Bergmann and contributors.`

phpunit.xml
`<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="bootstrap.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="true"
         stopOnRisky="true"
         timeoutForSmallTests="2"
         failOnRisky="true"
         enforceTimeLimit="true"
>
    <testsuites>
        <testsuite name="Package Test Suite">
            <directory suffix="Test.php">.</directory>
        </testsuite>
    </testsuites>

    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">../src</directory>
        </whitelist>
    </filter>
</phpunit>`

composer.json
`{
  "name": "obfuscated",
  "require": {
    "php": "^7.0"
  },
  "autoload": {
    "classmap": [
      "src/"
    ],
    "psr-4": {
      "obfuscated": "src/"
    }
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require-dev": {
    "phpunit/phpunit": "^7.3",
  }
}
`
AVeryRiskyTest.php
`<?php

class AVeryRiskyTest extends PHPUnit\Framework\TestCase {

	/**
	 * @small
	 */
	function testRisky() {
		sleep(10);
		assertTrue(true);
	}

}`

test output
`josh@Joshs-MacBook-Pro-2:~/.../unit-tests$ phpunit AVeryRiskyTest.php 
PHPUnit 7.3.2 by Sebastian Bergmann and contributors.

R                                                                   1 / 1 (100%)R

Time: 2.08 seconds, Memory: 10.00MB

There were 2 risky tests:

1) AVeryRiskyTest::testRisky
Execution aborted after 2 seconds

2) AVeryRiskyTest::testRisky
This test did not perform any assertions

/Users/josh/Projects/Candescent/mq-service-client/unit-tests/AVeryRiskyTest.php:8

OK, but incomplete, skipped, or risky tests!
Tests: 1, Assertions: 0, Risky: 2.`

It's not marked as a failure

**Comment by woodcockjosh** [comment]
inside `TestRunner.php` `wasSuccessful()` isn't true so I'm thinking that this block isn't evaluated because the test wasn't successful. Probably because of enforceTimeLimit
```
if ($arguments['failOnRisky'] && !$result->allHarmless()) {
                    exit(self::FAILURE_EXIT);
                }
```
