### ISSUE TITLE
How to programatically control execution of tests?

### ISSUE THREAD

**Issue by Danon** [sebastianbergmann/phpunit#4968]
Currently, I use `@group` for control of phpunit tests execution.

i run `--group unit` to run only the fast tests, and it works fine.

```
./phpunit --group unit
```

### Question

I have a lot of fast tests, 1900 of them, and I also have 500 of really slow tests. I don't want to assign `@group slow` to each of them, and I also think that would be a bad idea. I have a php function that can detect whether a certain test would be slow, and I would like to have two run configurations - one regular, and one that could fire the php function to tell whether a test should run or not.

I could do 
```
class Test extends TestCase {
  public function setUp() {
    if (myFunction()) {
      $this->markTestSkipped();
    }
  }
}
```

but then I couldn't control it from the run configuration, they would always be skipped.

How to do it?

Is there a way to programatically add a group to a test suite? Or some other way of programatically controling which tests should be run and which shouldn't?

**Comment by sebastianbergmann** [comment]
There is no way to "programatically control the execution of tests". And I do not think there should be one. The problem you describe is solved by the existing functionality that you describe.

**Comment by Danon** [comment]
@sebastianbergmann Thank you for your answer.

But what I described doesn't solve the issue, but it only "always skips" or "never skips". I miss an option to control the skip from the execution.

Okay, how about another idea.

1. Imagine a case where one has 3000 unit tests that run fast, matter of seconds.
2. Now Imagine a number of those tests, lets say 300, require some resoruceful verification, like it takes half a second for each test.
3. The resource'ful verification depends one the implementation details. 
4. So suite of 2700 lasts a second, and the reamining 300 last a minute, let's say.

What if I had a trait `AddiitonalAsserts` that I could use like that

```
class Test extends TestCase {
  use AdditionalAsserts;

  public function test() {
    $this->addiitonalAssert(something);
  } 
}
```

And I add those traits to certain tests that need it and take it away when tests don't need it, because the thing is really slow.

Is there a way for me to run just the tests that don't use that trait? And also all of them? Depending On the execution of phpunit?

If I add `@group slow` to the trait, and then exclude `slow` will this work? Or does the `@group` need to be at the TestCase itself?

**Comment by Danon** [comment]
@sebastianbergmann Oh my god it does work for `trait`s!

My good sir, PhpUnit never stops to amaze me. Excellent piece of work.
