### ISSUE TITLE
Test gathered multiple times for execution with `group` annotation

### ISSUE THREAD

**Issue by oojacoboo** [sebastianbergmann/phpunit#5502]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.3.2
| PHP version         | 8.1.21
| Installation Method | Composer

#### Summary

With a `phpunit.xml` config that defined multiple testsuites pointing to the same directory, when using the `group` annotation, PHPUnit looks through all testsuites and counts the annotated test multiple times, once per testsuite where the directory/test is defined

#### Current behavior

This wasn't happening on 9.x

This results in the test being executed once for each testsuite where the class is defined/included.

#### How to reproduce

Add a `group` annotated test in a test class.  Create more than one testsuite in your `phpunit.xml` file pointing to that file/directory.  Then call `phpunit --group your-group-string`. 

#### Expected behavior

Using the group annotation should not use testsuites for calculation, ideally.  If testsuites are the only means of identifying all test locations, then each test should be made unique in the final collection.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
> Create more than one testsuite in your `phpunit.xml` file pointing to that file/directory.

That sounds like #5487 which should be fixed in PHPUnit 10.3.3.

**Comment by oojacoboo** [comment]
Closed by https://github.com/sebastianbergmann/phpunit/issues/5487

**Comment by oojacoboo** [comment]
Unfortunately the issue still persists on 10.3.3.  I don't have a good testcase for this.  I guess I can create a lot of files and config to replicate it.  

The easiest way to test would be to take any existing repo available with phpunit, duplicate a testsuite in `phpunit.xml` with a different name, then add the `Group` annotation to any test with a given `group-name`.  Run `phpunit --group group-name`.

**Comment by sebastianbergmann** [comment]
The fact the test is run twice is unrelated to the usage of the filter configured using the `--group` CLI option.

Let me explain. Here is an example:

```
.
├── phpunit.xml
└── tests
    └── Issue5502Test.php
```
#### `phpunit.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/10.3/phpunit.xsd"
>
    <testsuites>
        <testsuite name="one">
            <directory>tests</directory>
        </testsuite>

        <testsuite name="two">
            <directory>tests</directory>
        </testsuite>
    </testsuites>
</phpunit>
```
#### `tests/Issue5502Test.php`
```php
<?php declare(strict_types=1);
namespace PHPUnit\TestFixture\Issue5502;

use PHPUnit\Framework\TestCase;

final class Issue5502Test extends TestCase
{
    public function testOne(): void
    {
        $this->assertTrue(true);
    }
}
```
#### PHPUnit 10.3
```
PHPUnit 10.3.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.10
Configuration: /tmp/issue-5502/phpunit.xml

..                                                                  2 / 2 (100%)

Time: 00:00.004, Memory: 8.00 MB

OK (2 tests, 2 assertions)
```
In the `phpunit.xml` configuration, we configure two test suites, `one` and `two`. The tests implemented in `tests/Issue5502Test.php` are configured to be part of both of these test suites.

When the test runner creates the test suite configured in the `phpunit.xml` configuration, it creates two test objects, because the test is part of two test suites.

After the test suite has been created, the filter configured using the `--group` CLI option is applied. The only thing this filter does is to check whether the groups defined for each test object match the group(s) that is/are to be run. Since both test objects are created for the same test method, and since that test method has metadata configuring it into the group to be run, the test is run twice.

This is expected behavior.

#### PHPUnit 9.6
```
PHPUnit 9.6.12 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 00:00.003, Memory: 6.00 MB

OK (1 test, 1 assertion)
```

The behavior of PHPUnit 9.6, however, which you can see above, is unexpected to me and I consider it to be a bug. PHPUnit 9.6 should also run the test twice.

**Comment by oojacoboo** [comment]
@sebastianbergmann ignoring this functionality change and overall design viewpoint, which I disagree with - focusing on the actual issue here.  How does one go about running one single test via annotation without it being run across multiple test-suites?

While debugging or developing, it's common to need to run a single test.  Having to type the full path to the file and method (if even possible), isn't exactly user-friendly, to say the least.  In the past, we've resorted to using a `group` annotation `phpunit --group test-only`.  This is useful if we run all tests and one or two tests fail and we need to debug just those tests.  This seems like a very practical use case and having those tests run multiple times is undesirable.

Aside from that use case, the group annotation, itself, with these changes, is much less useful and unclear in it's intended functionality.

**Comment by davidcorreia** [comment]
i agree with @oojacoboo 
it doesn't make much sense to run `phpunit --list-tests` and get duplicated results...

since this affects other tools and workflows, would be a consideration to add a `--unique` flag?
@sebastianbergmann what do you think?
